name: CI
on:
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Realizar os teste unitarios
              run: pip test
        