name: CI
on:
    pull:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
            - name: Realizar os teste unitarios
              run: pip install --upgrade pip
        